apiVersion: v1
kind: Service
metadata:
  name: mongosvc
  namespace: nsmongo
spec:
  selector:
    app: mongodb
  ports:
    - name: mongo
      protocol: TCP
      port: 27017
      targetPort: 27017