apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: javahpa
  namespace: nsmongo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: javadeplo
  minReplicas: {{.Values.replicasJava}}
  maxReplicas: {{.Values.replicasJavaMax}}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50