apiVersion: v1
kind: Service
metadata:
  name: javasvc
  namespace: {{.Values.nsName}}
spec:
  type: LoadBalancer
  selector:
    app: {{.Values.nombreApp}}
  ports:
    - protocol: TCP
      port: {{.Values.puertoApp}}
      targetPort: {{.Values.puertoApp}}