apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-ejemplo
  namespace: nspy
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ejemplo-deployment
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
