apiVersion: apps/v1
kind: Deployment
metadata:
  name: javadeplo
  namespace: nsmongo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: javatfg
  template:
    metadata:
      labels:
        app: javatfg
    spec:
      containers:
        - name: mongo-quarkus
          image: enriqueav99/javacicd:latest
          env:
            - name: QUARKUS_MONGODB_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: mongo-prueba-admin-system
                  key: connectionString.standardSrv
            - name: QUARKUS_MONGODB_CREDENTIALS_USERNAME
              value: ""
            - name: QUARKUS_MONGODB_CREDENTIALS_PASSWORD
              value: ""
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "256Mi"
              cpu: "256Mi"
            requests:
              memory: "256Mi"
              cpu: "256Mi"