apiVersion: v1
kind: Service
metadata:
  name: javasvc
  namespace: nsmongo
spec:
  type: LoadBalancer
  selector:
    app: javatfg
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080